<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Admin',
                'username' => 'admin',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '2000-01-06',
                'address' => 'anywhere',
                'email' => 'admin@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$rSUmYbKEQ8nJGZvxXVxb/OLVsrtN.xc0ifjSZRA9TMDxlBtfViGke',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 02:12:50',
                'updated_at' => '2023-02-02 02:12:50',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'masdaharia',
                'username' => 'masda',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '2000-01-10',
                'address' => 'Jl. Tanjung Pangimpuan',
                'email' => 'masda@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$GJ0Q8eqTCnepxVn/24JNOOWwsu3ZTD83LjU1d4pWauhL6RBQay3la',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 02:12:50',
                'updated_at' => '2023-02-02 07:34:30',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Marlia',
                'username' => 'lia',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '2002-08-30',
                'address' => 'Jl. Palupi Puskud',
                'email' => 'marlialia30@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$RUQh0QgxRdDlckHkWLfyOO7M6333FDSMItboQqLk/C4vM3TXhzfPO',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 02:34:43',
                'updated_at' => '2023-02-02 02:34:43',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Fadhilla Utami',
                'username' => 'ila',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '1999-03-29',
                'address' => 'Desa Sunju',
                'email' => 'fadhillautami29@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$tgYwUNIB6LkNYLatk/PF2ufggSe0MEx2CHcRPKgAnrlHC3/T/7fzu',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 02:40:49',
                'updated_at' => '2023-02-02 02:40:49',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Megawati M',
                'username' => 'mega',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '1999-11-06',
                'address' => 'Baliase',
                'email' => 'megawatim0611@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Y.gh09p2RSTo.Rjqv50iKufQzFESl7fE1OLzT0p//noG1RwqKLhC2',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 05:58:02',
                'updated_at' => '2023-02-02 05:58:02',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Nur Aimah',
                'username' => 'ima',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '2002-10-04',
                'address' => 'Jl Mangga',
                'email' => 'nuraimaima@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$6AdZzW9H6kXKNgX8SycBAeD.WvKhjiPf/0U5Z7dPD.fMztHrS1/0i',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 06:00:17',
                'updated_at' => '2023-02-02 06:00:17',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Citra Zul Nur Azizah',
                'username' => 'aziza',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '2005-09-26',
                'address' => 'Jl. Dayo Dara',
                'email' => 'citraaziza26@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Rik./McN29qaV.wrP87ObO72fPXpkeHYx6K9r9wOgksh95.wuuDCW',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 06:03:33',
                'updated_at' => '2023-02-02 06:03:33',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Nur Ainin Amalia',
                'username' => 'ainin',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '1999-02-01',
                'address' => 'Jl. Miangas',
                'email' => 'aininamalia@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$6NUNOPQvPFNF5CVtCoXWnexQbsUbZw/cgH3mu2HQUCZrl9F8GgdJW',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 06:05:30',
                'updated_at' => '2023-02-02 06:05:30',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Dewi Kartika Anggraini',
                'username' => 'tika',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '2004-12-06',
                'address' => 'Jl. Jati',
                'email' => 'kartikaanggraini06@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$6oOtJE1VV9Q6cwW5.2B3Kef64OQA7yxOzjxZLtLBVkVhZlXJ/HNp.',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 06:08:10',
                'updated_at' => '2023-02-02 06:08:10',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Faras Wati',
                'username' => 'faras',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '1999-09-11',
                'address' => 'Jl. Basuki Rahmat',
                'email' => 'faraswati11@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$kA89a60.vHZktmdC2vk9Z.stIQHqDjJA1Kbb1mAne8uUK8G15zwMG',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 06:10:17',
                'updated_at' => '2023-02-02 06:10:17',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Halisa Mutmainnah',
                'username' => 'halisa',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '1999-09-28',
                'address' => 'Jl. Lapatta',
                'email' => 'halisamutmainnah28@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Jj50q15g0i8.NkFMkfj7aOIhfY0IuPENq3Gz9OCqqCUzNjeQWJxzS',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 06:12:41',
                'updated_at' => '2023-02-02 06:12:41',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Hikmawati',
                'username' => 'hikma',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '1999-10-10',
                'address' => 'Jl. Tolamuotepu',
                'email' => 'hikmawati10@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$BWm6G/b.UKnnKcq964NjbOeK3rO6uLFciQ5KVTLXXyPqCjJ9pfYMy',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 06:15:10',
                'updated_at' => '2023-02-02 06:15:10',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Irmaliya',
                'username' => 'irma',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '1999-08-14',
                'address' => 'Jl. Sis Aljufri',
                'email' => 'irmaliya14@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Y3IME5VzmDcextCVNG0izeFbAsZ8F5T7x3qy5vreMCkCz42rYeeni',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 06:16:55',
                'updated_at' => '2023-02-02 06:16:55',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Rina Mega Utari',
                'username' => 'rina',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '2002-06-23',
                'address' => 'Jl. Cempedak',
                'email' => 'rinamega23@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$hdvZq/vUiqzj623iXZabbuLYNSJcOxUY78KAOhTfJGX48LfaR4GRa',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 06:21:52',
                'updated_at' => '2023-02-02 06:21:52',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Irmawati',
                'username' => 'wati',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '2000-10-01',
                'address' => 'Jl. Dewi Sartika',
                'email' => 'irmawati0110@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$n6nEraiSG6clfZJcZlH30eqYfBXw.8sg5mOx4FFFC3evWng3a8yTu',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 06:25:57',
                'updated_at' => '2023-02-02 06:25:57',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Jesya Karmelya',
                'username' => 'jesya',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '1999-08-10',
                'address' => 'Jl. Zebra',
                'email' => 'jesyakarmelyaadji@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$xTM6INcAeHmTumPJRlmmYupW.yzWD1kT2o4aNSeLzPysT48QAL9x2',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 06:27:55',
                'updated_at' => '2023-02-02 06:27:55',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Atma Puspita Dewi',
                'username' => 'atma',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '1999-08-27',
                'address' => 'Jl. Hangtua',
                'email' => 'atmapuspita@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$BVRDpDDQ9yo2b9nXQu19B.n1a0zv8SzB4cYdYPCKF..U9EOaXRj5i',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 06:30:40',
                'updated_at' => '2023-02-02 06:30:40',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Rani',
                'username' => 'rani',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '2003-03-28',
                'address' => 'Jl. Kedondong',
                'email' => 'ranirani28@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$/VWrvsJoMtFI2EdswSDd0eqZ3.Xd5EaHhjeEJo4erbj1zove2c0pa',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 06:33:17',
                'updated_at' => '2023-02-02 06:33:17',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Widi',
                'username' => 'widi',
                'jenis_kelamin' => 'Laki-laki',
                'profil' => 'default',
                'tanggal_lahir' => '2001-05-04',
                'address' => 'Jl. Kakatua',
                'email' => 'pujanggaanom@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$2BphiMU1ewsofus9Avy5m.o8t9MavJrQwiQUnZIsxtE8DhZ.yAeWy',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 06:35:38',
                'updated_at' => '2023-02-02 06:35:38',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Da\'i Saputra',
                'username' => 'putra',
                'jenis_kelamin' => 'Laki-laki',
                'profil' => 'default',
                'tanggal_lahir' => '1999-04-19',
                'address' => 'BTN ALyuna 2 Petobo',
                'email' => 'daisaputra1999@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$cL30kyC2pRgU3BOloJINqOlk735.DuuTbI3hR7ktEP9waAB0OIeFu',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 06:37:17',
                'updated_at' => '2023-02-02 06:37:17',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Khusnul Khotimah',
                'username' => 'hotim',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '1995-06-02',
                'address' => 'Jl. Jati',
                'email' => 'khusnulkhotimah@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$71ZE2VhC5aHBplSvden5muxT.Vce5G5KnXEmN7dodq8XLaqz5onRm',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 07:25:08',
                'updated_at' => '2023-02-02 07:25:08',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Syafira Ananda Toramai',
                'username' => 'fira',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '2004-03-15',
                'address' => 'Jl. Kelinci',
                'email' => 'Syafiratoramai15@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$cq8my2ouRwvgPHjjhlJDceNnfyquLvroi81kkW4J3IgNxZDfnfxGG',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 07:28:04',
                'updated_at' => '2023-02-02 07:28:04',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Idalle',
                'username' => 'lalle',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '1996-01-17',
                'address' => 'Jl. Tururuka',
                'email' => 'dalleidalle@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$/s//h7hUzgiPOn.5vJ8kNecva1.Er1jNwLnmAuAf.j13SLgpXf94.',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 08:11:26',
                'updated_at' => '2023-02-02 08:11:26',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Rabania',
                'username' => 'nia',
                'jenis_kelamin' => 'Perempuan',
                'profil' => 'default',
                'tanggal_lahir' => '2004-05-05',
                'address' => 'Jl. Miangas',
                'email' => 'rabaniania05@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$HM925YRHSfoSZKz1Lg1trOGOSKJlM/tkZQ0WU6omjOXTnmHawsJCG',
                'remember_token' => NULL,
                'created_at' => '2023-02-02 08:20:05',
                'updated_at' => '2023-02-02 08:20:05',
            ),
        ));
        
        
    }
}